# 开发环境配置
spring:
  
  # 数据库配置 - MySQL数据库
  datasource:
    url: jdbc:mysql://localhost:3306/greentech_platform?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: Qvdo1044
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-test-query: SELECT 1

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true

  # Redis配置 - Upstash
  data:
    redis:
      url: ${UPSTASH_REDIS_URL:redis://localhost:6379}
      password: ${UPSTASH_REDIS_PASSWORD:}
      timeout: 2000ms
      connect-timeout: 2000ms

# Supabase配置
supabase:
  url: ${SUPABASE_URL:https://your-project-ref.supabase.co}
  anon-key: ${SUPABASE_ANON_KEY:your-anon-key}
  service-role-key: ${SUPABASE_SERVICE_ROLE_KEY:your-service-role-key}

# 日志配置
logging:
  level:
    root: INFO
    com.greentech.platform: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 