# 测试环境配置 - 使用 H2 内存数据库
spring:
  profiles:
    active: test
  
  # 数据库配置 - H2 内存数据库
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true

  # H2 控制台配置
  h2:
    console:
      enabled: true
      path: /h2-console

  # Redis配置 - 禁用 Redis
  data:
    redis:
      enabled: false

# 模拟 Supabase 配置
supabase:
  url: http://localhost:8080
  anon-key: test-anon-key
  service-role-key: test-service-role-key

# 日志配置
logging:
  level:
    root: INFO
    com.greentech.platform: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /api 