server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: 绿色技术平台
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  # 数据库配置 - 使用MySQL数据库
  datasource:
    url: jdbc:mysql://localhost:3306/greentech_platform?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: Qvdo1044
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true

  # Redis配置 - Upstash
  data:
    redis:
      url: ${UPSTASH_REDIS_URL:redis://localhost:6379}
      password: ${UPSTASH_REDIS_PASSWORD:}
      timeout: 2000ms
      connect-timeout: 2000ms

  # 安全配置
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SUPABASE_URL:http://localhost:54321}/auth/v1

# Supabase配置
supabase:
  url: ${SUPABASE_URL:http://localhost:54321}
  anon-key: ${SUPABASE_ANON_KEY:your-anon-key}
  service-role-key: ${SUPABASE_SERVICE_ROLE_KEY:your-service-role-key}

# Stripe支付配置
stripe:
  api-key: ${STRIPE_SECRET_KEY:sk_test_xxx}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:whsec_xxx}
  public-key: ${STRIPE_PUBLIC_KEY:pk_test_xxx}

# 微信支付配置
wechat:
  pay:
    app-id: ${WECHAT_APP_ID:your-app-id}
    mch-id: ${WECHAT_MCH_ID:your-mch-id}
    api-key: ${WECHAT_API_KEY:your-api-key}
    cert-path: ${WECHAT_CERT_PATH:classpath:cert/apiclient_cert.p12}

# Resend邮件服务配置
resend:
  api-key: ${RESEND_API_KEY:re_xxx}
  from-email: ${RESEND_FROM_EMAIL:noreply@greentech.com}

# OpenRouter AI服务配置
openrouter:
  api-key: ${OPENROUTER_API_KEY:sk-or-xxx}
  base-url: ${OPENROUTER_BASE_URL:https://openrouter.ai/api/v1}

# 应用配置
app:
  name: 绿色技术平台
  version: 1.0.0
  domain: ${APP_DOMAIN:localhost:8080}
  frontend-url: ${FRONTEND_URL:http://localhost:3000}
  jwt:
    secret: ${JWT_SECRET:your-secret-key-should-be-very-long-and-secure}
    expiration: ${JWT_EXPIRATION:86400} # 24小时

# 文件上传配置
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
      enabled: true

  # 调度任务配置
  task:
    scheduling:
      pool:
        size: 2

# 日志配置
logging:
  level:
    com.greentech.platform: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Actuator健康检查
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

# Swagger文档配置
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

---
# 开发环境配置
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    com.greentech.platform: DEBUG

---
# 生产环境配置
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: WARN
    com.greentech.platform: INFO